# Generated by Django 6.1.2 on 2026-10-07 19:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=300, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('full_address', models.CharField(max_length=500)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full_address', models.CharField(max_length=500)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('grid_key', models.CharField(max_length=40, unique=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('verdict', models.CharField(blank=True, max_length=300)),
                ('place_count', models.PositiveIntegerField(default=0)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['-score'], name='areas_area_score_4aae75_idx'), models.Index(fields=['-created_at'], name='areas_area_created_95d4c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='CategoryScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('grocery', 'Groceries'), ('health', 'Hospitals & clinics'), ('transport', 'Bus & metro'), ('pharmacy', 'Pharmacies'), ('education', 'Schools & colleges'), ('parks', 'Parks'), ('food', 'Food & cafés'), ('banking', 'ATMs & banks'), ('safety', 'Police & fire'), ('fitness', 'Gyms & sports')], max_length=20)),
                ('points', models.FloatField(default=0)),
                ('max_points', models.PositiveSmallIntegerField()),
                ('place_count', models.PositiveIntegerField(default=0)),
                ('nearest_name', models.CharField(blank=True, max_length=200)),
                ('nearest_metres', models.PositiveIntegerField(blank=True, null=True)),
                ('nearest_walk_minutes', models.FloatField(blank=True, null=True)),
                ('walk_time_is_estimate', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_scores', to='areas.area')),
            ],
            options={
                'ordering': ['-max_points', 'category'],
                'constraints': [models.UniqueConstraint(fields=('area', 'category'), name='one_score_per_category')],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('grocery', 'Groceries'), ('health', 'Hospitals & clinics'), ('transport', 'Bus & metro'), ('pharmacy', 'Pharmacies'), ('education', 'Schools & colleges'), ('parks', 'Parks'), ('food', 'Food & cafés'), ('banking', 'ATMs & banks'), ('safety', 'Police & fire'), ('fitness', 'Gyms & sports')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('distance_metres', models.PositiveIntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='areas.area')),
            ],
            options={
                'ordering': ['distance_metres'],
                'indexes': [models.Index(fields=['area', 'category'], name='areas_place_area_id_92c577_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='areas.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'area'), name='save_area_once')],
            },
        ),
    ]
